ConcertinaController=window.ConcertinaController||{};
ConcertinaController.panelImageLoad=function(a){a=$(a).attr("id");jPanel=$("#"+a).parents(".concertina--item");ConcertinaController.setupPanelBindings(jPanel);ConcertinaController.configureForSize(jPanel);if($("html").hasClass("ie8")&&jPanel.find(".lazyIE8").attr("src")!=jPanel.find(".lazyIE8").data("original")){a=jPanel.find(".placeholderIE8").data("offsetpercent");var c=jPanel.find(".lazyIE8").data("original");jPanel.find(".lazyIE8").attr("src",c).attr("onload","$(this).parent().find('.placeholderIE8').hide().remove();").data("offsetpercent",
a).css({display:"block"})}};var sumPanels=function(){var a=0;return function(){var c=$(".concertina--item").length;a+=1;a==c&&$(window).trigger("TNZ.Module.Concertina.loaded")}};ConcertinaController.updatePanelCount=sumPanels();ConcertinaController.delay=function(){var a=0;return function(c,b){clearTimeout(a);a=setTimeout(c,b)}}();ConcertinaController.setupBindings=function(){$(window).on("resize",function(){ConcertinaController.delay(function(a){ConcertinaController.onResize()},400)})};
ConcertinaController.onResize=function(){var a=0;$(".concertina").each(function(){$(this).find(".concertina--item").each(function(){var c=$(this);ConcertinaController.configureForSize(c);a++})});ConcertinaController.reDrawConcertina()};
ConcertinaController.reDrawConcertina=function(a){$(".concertina").each(function(a){a=$(this);ConcertinaController.updateConcertinaSettings(a);var b=ConcertinaController.getConcertinaSettings(a);b.items.each(function(){var a=$(this);ConcertinaController.resetPanels(a,b);ConcertinaController.reDrawPanel(a)})})};
ConcertinaController.updateConcertinaSettings=function(a){var c=a.attr("id");ConcertinaController[c]={};var b=ConcertinaController[c];b.id=c;b.concertinaWidth=a.width();b.items=a.find(".concertina--item");b.wrap=a.find(".concertina--wrap");b.numberOfPanels=b.items.length;b.originalPanelSize=100/b.numberOfPanels;b.originalPanelSizePercent=b.originalPanelSize+"%";b.panelWidth=b.concertinaWidth/b.numberOfPanels;b.expandedPanelSize=0.85*b.concertinaWidth;b.leftOvers=15/(b.numberOfPanels-1)/100*b.concertinaWidth};
ConcertinaController.initialiseConcertina=function(a){if(!(800<$(window).width())){var c=a.parents(".concertinablock").prev(".headingblock").find(".js-heading-link");a.append(c)}};ConcertinaController.getConcertinaSettings=function(a){var c=a.attr("id");"undefined"==typeof ConcertinaController[c]&&(ConcertinaController.updateConcertinaSettings(a),ConcertinaController.initialiseConcertina(a));return ConcertinaController[c]};
ConcertinaController.setPanelState=function(a,c){switch(c){case "normal":a.removeClass("hovered");break;case "hovered-normal":a.addClass("hovered");break;case "normal-hovered-sibling":a.css({opacity:"0.75"});break;case "large":a.addClass("active");a.parents(".concertina").addClass("has-active-panel");break;case "small":a.css({opacity:"0.75"})}};ConcertinaController.createClosureEvent=function(a,c,b,d){return function(e){return d.apply(this,[e,a,c,b])}};
ConcertinaController.panelClick=function(a,c,b,d){var e=ConcertinaController.getConcertinaSettings(b);if(ConcertinaController.isDesktop()&&!c.hasClass("active")){ConcertinaController.resetPanels(c,e);a=c.find(".picture img");d=c.siblings();var f=c.find(".concertina--meta");d.width(e.leftOvers);d.each(function(){ConcertinaController.resetPanelOffsets($(this),e,e.leftOvers)});c.addClass("active");b.addClass("has-active-panel");a.css({left:-(a.width()/2)});c.width(e.expandedPanelSize+"px");var g=c.find(".zoom-map");
!1===g.hasClass("zoomed-in")&&!1===$("html").hasClass("touch")&&!1===$("html").hasClass("ie8")&&setTimeout(function(){$.zoommap.zoomIn(g)},1200);f.velocity({display:"block",opacity:1},500);ConcertinaController.resetPanelOffsets(c,e,e.expandedPanelSize)}};
ConcertinaController.panelHoverOn=function(a,c,b,d){a=ConcertinaController.getConcertinaSettings(b);if(ConcertinaController.isDesktop()){ConcertinaController.setPanelState(c,"hovered-normal");d=a.originalPanelSize-1;var e=a.originalPanelSize+a.numberOfPanels-1;b.find(".concertina--item:not(.hovered)").each(function(){ConcertinaController.setPanelState($(this),"normal-hovered-sibling")});b.hasClass("has-active-panel")||(c.css({width:e+"%"}),c.siblings().css({width:d+"%"}),ConcertinaController.resetPanelOffsets(c,
a,a.panelWidth+a.concertinaWidth*(a.numberOfPanels-1)/100))}};ConcertinaController.panelHoverOff=function(a,c,b,d){a=ConcertinaController.getConcertinaSettings(b);ConcertinaController.isDesktop()&&(ConcertinaController.setPanelState(c,"normal"),b.find(".concertina--item").css({opacity:1}),b.hasClass("has-active-panel")||(b.find(".concertina--item").css({width:a.originalPanelSizePercent}),ConcertinaController.resetPanelOffsets(c,a)))};
ConcertinaController.panelCloseBtnClick=function(a,c,b,d){var e=ConcertinaController.getConcertinaSettings(b);if(ConcertinaController.isDesktop())return b.find(".concertina--item").each(function(){ConcertinaController.resetPanels($(this),e)}),b.find(".concertina--item").each(function(){ConcertinaController.resetPanelOffsets($(this),e)}),!1};ConcertinaController.mobileTitleClick=function(a,c,b,d){if(!ConcertinaController.isDesktop())return c.find(".concertina--intro-meta").toggleClass("open"),!1};
ConcertinaController.panelLoveClick=function(a,c,b,d){a=c.find(".js-lovethis");a.hasClass("in-love")?$(window).trigger("TNZ.Module.Concertina.love.remove",c.data("relatedobjectid")):(a.addClass("in-love"),$(window).trigger({type:"TNZ.Module.Concertina.love.clicked",elem:this},c));$(this).hasClass("js-panellove")&&(a="TNZLoveThis_"+TNZ.initialRequestConfig.marketDefaultLanguageMarket.toUpperCase(),b={path:"/",domain:".newzealand.com",expires:30},$.cookie(a)||(c.find(".tooltip").fadeIn().delay(3E3).fadeOut(),
$.cookie(a,!0,b)));return!1};ConcertinaController.resetPanelOffsets=function(a,c,b){a=ConcertinaController.getPanelImageInfo(a);c=ConcertinaController.getImageOffset(a.image[0].clientWidth,"undefined"==typeof b?c.panelWidth:b,a.offsetpercent);a.image.css({left:c+"px"})};
ConcertinaController.getPanelImageInfo=function(a){var c={};$("html").hasClass("ie8")?c.image=a.find("img.picture"):c.image=a.find(".picture img");c.offsetpercent=50;c.image.length&&"undefined"!=c.image.attr("src")&&""!=c.image.attr("src")&&null!=c.image.attr("src")?$("html").hasClass("ie8")?c.offsetpercent=parseInt(c.image.data("offsetpercent")):c.offsetpercent=parseInt(c.image.parent().data("offsetpercent")):(c.image=a.find(".placeholder"),c.offsetpercent=parseInt(c.image.data("offsetpercent")));
$("html").hasClass("ie8")||ConcertinaController.fixLayout(a);return c};ConcertinaController.fixLayout=function(){var a=!1,c=0;return function(b){if(!$("html").hasClass("ie8")&&!1===a&&ConcertinaController.isDesktop())if(c++,b=b.parents(".concertina").find(".concertina--item"),1<b.length&&b.first().offset().top!==b.last().offset().top){for(var d=6,e=30,f=b.first().offset().top;f!==b.last().offset().top&&0!==e;)b.css({"margin-right":"-"+d+"px"}),d++,e--;a=!0}else if(60<c||1===b.length)a=!0;return a}}();
ConcertinaController.isDesktop=function(){return 800<$(window).width()?!0:!1};ConcertinaController.configureForSize=function(a){var c=ConcertinaController.isDesktop(),b=a.parents(".concertina"),b=ConcertinaController.getConcertinaSettings(b);c?a.parents(".concertina").hasClass("has-active-panel")||(ConcertinaController.getPanelImageInfo(a),a.css({width:b.originalPanelSizePercent}),ConcertinaController.resetPanelOffsets(a,b)):a.css({width:"auto"})};
ConcertinaController.setupPanelBindings=function(a){var c=a.data("bindingsSet");if(!1==c||!c){a.data("bindingsSet",!0);var b=a.parents(".concertina"),c=ConcertinaController.getConcertinaSettings(b);a.on("click",ConcertinaController.createClosureEvent(a,b,c,ConcertinaController.panelClick));a.find(".js-close-panel").on("click",ConcertinaController.createClosureEvent(a,b,c,ConcertinaController.panelCloseBtnClick));a.find(".intro-title, .concertina--image").on("click",ConcertinaController.createClosureEvent(a,
b,c,ConcertinaController.mobileTitleClick));a.find(".js-rel-obj-link").on("click",function(){if(!ConcertinaController.isDesktop()&&a.find(".concertina--intro-meta").hasClass("open")){var b=$(this).data("href");document.location.href=b}});a.find(".js-lovethis").on("click",ConcertinaController.createClosureEvent(a,b,c,ConcertinaController.panelLoveClick));ConcertinaController.updatePanelCount();$(window).on("TNZ.Module.Concertina.love.remove",function(a,c){b.find("[data-relatedobjectid\x3d"+c+"] .js-lovethis").removeClass("in-love")})}};
ConcertinaController.reDrawPanel=function(a){var c=ConcertinaController.isDesktop(),b=a.parents(".concertina"),b=ConcertinaController.getConcertinaSettings(b);ConcertinaController.getPanelImageInfo(a);c&&(a.css({width:b.originalPanelSizePercent}),ConcertinaController.resetPanelOffsets(a,b))};ConcertinaController.getImageOffset=function(a,c,b){b=c/2-b/100*a;a=-1*(a-c);0<=b&&(b=0);b<a&&(b=a);return Math.round(b)};
ConcertinaController.resetPanels=function(a,c){var b=a.siblings(".active");b.removeClass("active");a.parents(".concertina").removeClass("has-active-panel");var d=b.find(".concertina--image img"),b=b.find(".concertina--meta"),e=ConcertinaController.isDesktop();d.css({left:-(d.width()/2)-d.data("offset")});b.velocity({opacity:0});e&&a.css({width:c.originalPanelSizePercent});ConcertinaController.resetPanelOffsets(a,c.originalPanelSizePercent);return!1};ConcertinaController.setupBindings();
/*46587 g*//* TNZPRDWEB1 */