(function(c){var d;c.extend({poiblock:{init:function(){d=c(".js-contentBlockPOI");m()}}});var m=function(){d.each(function(d,m){var l=c(m).find(".js-poi-card-content"),u=0;l.each(function(d,l){u=Math.max(u,c(l).height())});l.height(u)})}})(jQuery);$(document).ready($.poiblock.init);
$().ready(function(){$(window).on("TNZ.HeroVideo.FullscreenOn",function(c){var m=$(".collapsible-panel:first");if($("body").hasClass("full-screen")){var q=m.data("offset");m.css({marginTop:q});$(window).on("scroll",function(){var c=q+$(window).scrollTop();0>c?m.css({marginTop:c}):m.css({marginTop:0})}).scroll()}else m.css({marginTop:"0"})});var c=$(".deal.collapsible-panel");c.on("click","h4",function(){if(!c.hasClass("animating")){c.addClass("animating");var d=$(this).next(".content");c.hasClass("open")?
d.children().velocity({opacity:0},500,function(){d.velocity("slideUp",500,function(){c.removeClass("open");c.removeClass("animating")})}):d.velocity("slideDown",500,function(){d.children().velocity({opacity:1},500,function(){c.addClass("open");c.removeClass("animating")})})}})});
!function(c,d,m,q){function G(a){for(var b=-1,g=a?a.length:0,f=[];++b<g;){var w=a[b];w&&f.push(w)}return f}function l(a){a=t.data(a,F);return null===a?q:a}function u(a){return function(b){return Math.round(b*a)*(1/a)}}function z(a,b){var g=a;return h.isString(a)?f.Easings[a]||(g=!1):g=h.isArray(a)&&1===a.length?u.apply(null,a):h.isArray(a)&&2===a.length?I.apply(null,a.concat([b])):h.isArray(a)&&4===a.length?x.apply(null,a):!1,!1===g&&(g=f.Easings[f.defaults.easing]?f.defaults.easing:H),g}function D(r){if(r){r=
(new Date).getTime();for(var b=0,g=f.State.calls.length;g>b;b++)if(f.State.calls[b]){var c=f.State.calls[b],w=c[0],p=c[2],K=c[3];K||(K=f.State.calls[b][3]=r-16);for(var A=Math.min((r-K)/p.duration,1),d=0,t=w.length;t>d;d++){var n=w[d],m=n.element;if(l(m)){var u=!1;p.display&&"none"!==p.display&&a.setPropertyValue(m,"display",p.display);p.visibility&&"hidden"!==p.visibility&&a.setPropertyValue(m,"visibility",p.visibility);for(var e in n)if("element"!==e){var k,v=n[e],L=h.isString(v.easing)?f.Easings[v.easing]:
v.easing;if(k=1===A?v.endValue:v.startValue+(v.endValue-v.startValue)*L(A),v.currentValue=k,a.Hooks.registered[e]){var M=a.Hooks.getRoot(e);(L=l(m).rootPropertyValueCache[M])&&(v.rootPropertyValue=L)}v=a.setPropertyValue(m,e,v.currentValue+(0===parseFloat(k)?"":v.unitType),v.rootPropertyValue,v.scrollData);a.Hooks.registered[e]&&(l(m).rootPropertyValueCache[M]=a.Normalizations.registered[M]?a.Normalizations.registered[M]("extract",null,v[1]):v[1]);"transform"===v[0]&&(u=!0)}p.mobileHA&&l(m).transformCache.translate3d===
q&&(l(m).transformCache.translate3d="(0px, 0px, 0px)",u=!0);u&&a.flushTransformCache(m)}}p.display&&"none"!==p.display&&(f.State.calls[b][2].display=!1);p.visibility&&"hidden"!==p.visibility&&(f.State.calls[b][2].visibility=!1);p.progress&&p.progress.call(c[1],c[1],A,Math.max(0,K+p.duration-r),K);1===A&&C(b)}}f.State.isTicking&&s(D)}function C(r,b){if(!f.State.calls[r])return!1;for(var g=f.State.calls[r][0],c=f.State.calls[r][1],w=f.State.calls[r][2],p=f.State.calls[r][4],K=!1,h=0,d=g.length;d>h;h++){var n=
g[h].element;if(b||w.loop||("none"===w.display&&a.setPropertyValue(n,"display",w.display),"hidden"===w.visibility&&a.setPropertyValue(n,"visibility",w.visibility)),(t.queue(n)[1]===q||!/\.velocityQueueEntryFlag/i.test(t.queue(n)[1]))&&l(n)){l(n).isAnimating=!1;l(n).rootPropertyValueCache={};var m=!1;t.each(l(n).transformCache,function(a,e){var k=/^scale/.test(a)?1:0;RegExp("^\\("+k+"[^.]").test(e)&&(m=!0,delete l(n).transformCache[a])});w.mobileHA&&(m=!0,delete l(n).transformCache.translate3d);m&&
a.flushTransformCache(n);a.Values.removeClass(n,"animating")}if(!b&&w.complete&&!w.loop&&h===d-1)try{w.complete.call(c,c)}catch(s){setTimeout(function(){throw s;},1)}p&&p(c);!1!==w.queue&&t.dequeue(n,w.queue)}f.State.calls[r]=!1;g=0;for(c=f.State.calls.length;c>g;g++)if(!1!==f.State.calls[g]){K=!0;break}!1===K&&(f.State.isTicking=!1,delete f.State.calls,f.State.calls=[])}var F="velocity",y=400,H="swing",E=function(){if(m.documentMode)return m.documentMode;for(var a=7;4<a;a--){var b=m.createElement("div");
if(b.innerHTML="\x3c!--[if IE "+a+"]\x3e\x3cspan\x3e\x3c/span\x3e\x3c![endif]--\x3e",b.getElementsByTagName("span").length)return a}return q}(),n=function(){var a=0;return d.webkitRequestAnimationFrame||d.mozRequestAnimationFrame||function(b){var g,f=(new Date).getTime();return g=Math.max(0,16-(f-a)),a=f+g,setTimeout(function(){b(f+g)},g)}}(),s=d.requestAnimationFrame||n,h={isString:function(a){return"string"==typeof a},isArray:Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)},
isFunction:function(a){return"[object Function]"===Object.prototype.toString.call(a)},isNode:function(a){return a&&a.nodeType},isNodeList:function(a){return"object"==typeof a&&/^\[object (HTMLCollection|NodeList|Object)\]$/.test(Object.prototype.toString.call(a))&&a.length!==q&&(0===a.length||"object"==typeof a[0]&&0<a[0].nodeType)},isWrapped:function(a){return a&&(a.jquery||d.Zepto&&d.Zepto.zepto.isZ(a))},isSVG:function(a){return d.SVGElement&&a instanceof SVGElement}},t=d.jQuery||c.Velocity&&c.Velocity.Utilities;
if(!t)throw Error("Velocity: Either jQuery or Velocity's jQuery shim must first be loaded.");if(c.Velocity!==q&&!c.Velocity.Utilities)throw Error("Velocity: Namespace is occupied.");if(7>=E){if(d.jQuery)return void(d.jQuery.fn.velocity=d.jQuery.fn.animate);throw Error("Velocity: For IE\x3c\x3d7, Velocity falls back to jQuery, which must first be loaded.");}if(8===E&&!d.jQuery)throw Error("Velocity: For IE8, Velocity requires jQuery to be loaded. (Velocity's jQuery shim does not work with IE8.)");
var f=c.Velocity=c.velocity={State:{isMobile:/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent),isAndroid:/Android/i.test(navigator.userAgent),isGingerbread:/Android 2\.3\.[3-7]/i.test(navigator.userAgent),isChrome:d.chrome,prefixElement:m.createElement("div"),prefixMatches:{},scrollAnchor:null,scrollPropertyLeft:null,scrollPropertyTop:null,isTicking:!1,calls:[]},CSS:{},Utilities:d.jQuery,Sequences:{},Easings:{},Promise:d.Promise,defaults:{queue:"",duration:y,
easing:H,begin:null,complete:null,progress:null,display:null,loop:!1,delay:!1,mobileHA:!0,_cacheValues:!0},animate:function(){},mock:!1,version:{major:0,minor:8,patch:0},debug:!1};d.pageYOffset!==q?(f.State.scrollAnchor=d,f.State.scrollPropertyLeft="pageXOffset",f.State.scrollPropertyTop="pageYOffset"):(f.State.scrollAnchor=m.documentElement||m.body.parentNode||m.body,f.State.scrollPropertyLeft="scrollLeft",f.State.scrollPropertyTop="scrollTop");f.State.isMobile||m.hidden===q||m.addEventListener("visibilitychange",
function(){m.hidden?(s=function(a){return setTimeout(function(){a(!0)},16)},D()):s=d.requestAnimationFrame||n});var x=function(){return function(a,b,g,f){if(4!==arguments.length)return!1;for(var c=0;4>c;++c)if("number"!=typeof arguments[c]||isNaN(arguments[c])||!isFinite(arguments[c]))return!1;return a=Math.min(a,1),g=Math.min(g,1),a=Math.max(a,0),g=Math.max(g,0),function(p){if(a!==b||g!==f){a:{for(var c=p,h=0;8>h;++h){var w;w=c;var d=a,n=g;w=3*(1-3*n+3*d)*w*w+2*(3*n-6*d)*w+3*d;if(0===w){p=c;break a}c-=
((((1-3*g+3*a)*c+(3*g-6*a))*c+3*a)*c-p)/w}p=c}p*=((1-3*f+3*b)*p+(3*f-6*b))*p+3*b}return p}}}(),I=function(){function a(b,r,f){var p=b.v+f.dv*r;return{dx:p,dv:-b.tension*(b.x+f.dx*r)-b.friction*p}}function b(b,f){var c={dx:b.v,dv:-b.tension*b.x-b.friction*b.v},p=a(b,0.5*f,c),h=a(b,0.5*f,p),d=a(b,f,h),n=1/6*(c.dv+2*(p.dv+h.dv)+d.dv);return b.x+=1/6*(c.dx+2*(p.dx+h.dx)+d.dx)*f,b.v+=n*f,b}return function N(a,r,f){var c,h,d,n={x:-1,v:0,tension:null,friction:null},l=[0],t=0;a=parseFloat(a)||500;r=parseFloat(r)||
20;f=f||null;n.tension=a;n.friction=r;for((c=null!==f)?(t=N(a,r),h=t/f*0.016):h=0.016;d=b(d||n,h),l.push(1+d.x),t+=16,1E-4<Math.abs(d.x)&&1E-4<Math.abs(d.v););return c?function(a){return l[a*(l.length-1)|0]}:t}}();!function(){f.Easings.linear=function(a){return a};f.Easings.swing=function(a){return 0.5-Math.cos(a*Math.PI)/2};f.Easings.spring=function(a){return 1-Math.cos(4.5*a*Math.PI)*Math.exp(6*-a)};f.Easings.ease=x(0.25,0.1,0.25,1);f.Easings["ease-in"]=x(0.42,0,1,1);f.Easings["ease-out"]=x(0,0,
0.58,1);f.Easings["ease-in-out"]=x(0.42,0,0.58,1);var a={};t.each(["Quad","Cubic","Quart","Quint","Expo"],function(b,g){a[g]=function(a){return Math.pow(a,b+2)}});t.extend(a,{Sine:function(a){return 1-Math.cos(a*Math.PI/2)},Circ:function(a){return 1-Math.sqrt(1-a*a)},Elastic:function(a){return 0===a||1===a?a:-Math.pow(2,8*(a-1))*Math.sin((80*(a-1)-7.5)*Math.PI/15)},Back:function(a){return a*a*(3*a-2)},Bounce:function(a){for(var g,r=4;a<((g=Math.pow(2,--r))-1)/11;);return 1/Math.pow(4,3-r)-7.5625*
Math.pow((3*g-2)/22-a,2)}});t.each(a,function(a,g){f.Easings["easeIn"+a]=g;f.Easings["easeOut"+a]=function(a){return 1-g(1-a)};f.Easings["easeInOut"+a]=function(a){return 0.5>a?g(2*a)/2:1-g(-2*a+2)/2}})}();var a=f.CSS={RegEx:{valueUnwrap:/^[A-z]+\((.*)\)$/i,wrappedValueAlreadyExtracted:/[0-9.]+ [0-9.]+ [0-9.]+( [0-9.]+)?/,valueSplit:/([A-z]+\(.+\))|(([A-z0-9#-.]+?)(?=\s|$))/gi},Hooks:{templates:{color:["Red Green Blue Alpha","255 255 255 1"],backgroundColor:["Red Green Blue Alpha","255 255 255 1"],
borderColor:["Red Green Blue Alpha","255 255 255 1"],borderTopColor:["Red Green Blue Alpha","255 255 255 1"],borderRightColor:["Red Green Blue Alpha","255 255 255 1"],borderBottomColor:["Red Green Blue Alpha","255 255 255 1"],borderLeftColor:["Red Green Blue Alpha","255 255 255 1"],outlineColor:["Red Green Blue Alpha","255 255 255 1"],fill:["Red Green Blue Alpha","255 255 255 1"],stroke:["Red Green Blue Alpha","255 255 255 1"],stopColor:["Red Green Blue Alpha","255 255 255 1"],textShadow:["Color X Y Blur",
"black 0px 0px 0px"],boxShadow:["Color X Y Blur Spread","black 0px 0px 0px 0px"],clip:["Top Right Bottom Left","0px 0px 0px 0px"],backgroundPosition:["X Y","0% 0%"],transformOrigin:["X Y Z","50% 50% 0px"],perspectiveOrigin:["X Y","50% 50%"]},registered:{},register:function(){var r,b,g;if(E)for(r in a.Hooks.templates)b=a.Hooks.templates[r],g=b[0].split(" "),b=b[1].match(a.RegEx.valueSplit),"Color"===g[0]&&(g.push(g.shift()),b.push(b.shift()),a.Hooks.templates[r]=[g.join(" "),b.join(" ")]);for(r in a.Hooks.templates){b=
a.Hooks.templates[r];g=b[0].split(" ");for(var f in g)a.Hooks.registered[r+g[f]]=[r,f]}},getRoot:function(r){var b=a.Hooks.registered[r];return b?b[0]:r},cleanRootPropertyValue:function(r,b){return a.RegEx.valueUnwrap.test(b)&&(b=b.match(a.Hooks.RegEx.valueUnwrap)[1]),a.Values.isCSSNullValue(b)&&(b=a.Hooks.templates[r][1]),b},extractValue:function(r,b){var g=a.Hooks.registered[r];if(g){var f=g[1];return b=a.Hooks.cleanRootPropertyValue(g[0],b),b.toString().match(a.RegEx.valueSplit)[f]}return b},injectValue:function(r,
b,g){if(r=a.Hooks.registered[r]){var f,c=r[1];return g=a.Hooks.cleanRootPropertyValue(r[0],g),f=g.toString().match(a.RegEx.valueSplit),f[c]=b,f.join(" ")}return g}},Normalizations:{registered:{clip:function(r,b,g){switch(r){case "name":return"clip";case "extract":var f;return a.RegEx.wrappedValueAlreadyExtracted.test(g)?f=g:(f=g.toString().match(a.RegEx.valueUnwrap),f=f?f[1].replace(/,(\s+)?/g," "):g),f;case "inject":return"rect("+g+")"}},opacity:function(a,b,g){if(8>=E)switch(a){case "name":return"filter";
case "extract":return(a=g.toString().match(/alpha\(opacity=(.*)\)/i))?a[1]/100:1;case "inject":return b.style.zoom=1,1<=parseFloat(g)?"":"alpha(opacity\x3d"+parseInt(100*parseFloat(g),10)+")"}else switch(a){case "name":return"opacity";case "extract":return g;case "inject":return g}}},register:function(){function r(a){var b;return a=a.replace(/^#?([a-f\d])([a-f\d])([a-f\d])$/i,function(a,b,g,f){return b+b+g+g+f+f}),b=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a),b?"rgb("+(parseInt(b[1],16)+" "+
parseInt(b[2],16)+" "+parseInt(b[3],16))+")":"rgb(0 0 0)"}var b="translateX translateY scale scaleX scaleY skewX skewY rotateZ".split(" ");9>=E||f.State.isGingerbread||(b=b.concat(["transformPerspective","translateZ","scaleZ","rotateX","rotateY"]));for(var g=0,c=b.length;c>g;g++)!function(){var r=b[g];a.Normalizations.registered[r]=function(a,b,g){switch(a){case "name":return"transform";case "extract":return l(b).transformCache[r]===q?/^scale/i.test(r)?1:0:l(b).transformCache[r].replace(/[()]/g,"");
case "inject":a=!1;switch(r.substr(0,r.length-1)){case "translate":a=!/(%|px|em|rem|\d)$/i.test(g);break;case "scal":case "scale":f.State.isAndroid&&l(b).transformCache[r]===q&&1>g&&(g=1);a=!/(\d)$/i.test(g);break;case "skew":a=!/(deg|\d)$/i.test(g);break;case "rotate":a=!/(deg|\d)$/i.test(g)}return a||(l(b).transformCache[r]="("+g+")"),l(b).transformCache[r]}}}();for(var h="fill stroke stopColor color backgroundColor borderColor borderTopColor borderRightColor borderBottomColor borderLeftColor outlineColor".split(" "),
g=0,c=h.length;c>g;g++)!function(){var b=h[g];a.Normalizations.registered[b]=function(g,f,c){switch(g){case "name":return b;case "extract":if(!a.RegEx.wrappedValueAlreadyExtracted.test(c)){var h;g={aqua:"rgb(0, 255, 255);",black:"rgb(0, 0, 0)",blue:"rgb(0, 0, 255)",fuchsia:"rgb(255, 0, 255)",gray:"rgb(128, 128, 128)",green:"rgb(0, 128, 0)",lime:"rgb(0, 255, 0)",maroon:"rgb(128, 0, 0)",navy:"rgb(0, 0, 128)",olive:"rgb(128, 128, 0)",purple:"rgb(128, 0, 128)",red:"rgb(255, 0, 0)",silver:"rgb(192, 192, 192)",
teal:"rgb(0, 128, 128)",white:"rgb(255, 255, 255)",yellow:"rgb(255, 255, 0)"};/^[A-z]+$/i.test(c)?h=g[c]!==q?g[c]:g.black:/^#([A-f\d]{3}){1,2}$/i.test(c)?h=r(c):/^rgba?\(/i.test(c)||(h=g.black);c=(h||c).toString().match(a.RegEx.valueUnwrap)[1].replace(/,(\s+)?/g," ")}return 8>=E||3!==c.split(" ").length||(c+=" 1"),c;case "inject":return 8>=E?4===c.split(" ").length&&(c=c.split(/\s+/).slice(0,3).join(" ")):3===c.split(" ").length&&(c+=" 1"),(8>=E?"rgb":"rgba")+"("+c.replace(/\s+/g,",").replace(/\.(\d)+(?=,)/g,
"")+")"}}}()}},Names:{camelCase:function(a){return a.replace(/-(\w)/g,function(a,g){return g.toUpperCase()})},SVGAttribute:function(a){var b="width|height|x|y|cx|cy|r|rx|ry|x1|x2|y1|y1";return(E||f.State.isAndroid&&!f.State.isChrome)&&(b+="|transform"),RegExp("^("+b+")$","i").test(a)},prefixCheck:function(a){if(f.State.prefixMatches[a])return[f.State.prefixMatches[a],!0];for(var b=["","Webkit","Moz","ms","O"],g=0,c=b.length;c>g;g++){var d;if(d=0===g?a:b[g]+a.replace(/^\w/,function(a){return a.toUpperCase()}),
h.isString(f.State.prefixElement.style[d]))return f.State.prefixMatches[a]=d,[d,!0]}return[a,!1]}},Values:{isCSSNullValue:function(a){return 0==a||/^(none|auto|transparent|(rgba\(0, ?0, ?0, ?0\)))$/i.test(a)},getUnitType:function(a){return/^(rotate|skew)/i.test(a)?"deg":/(^(scale|scaleX|scaleY|scaleZ|alpha|flexGrow|flexHeight|zIndex|fontWeight)$)|((opacity|red|green|blue|alpha)$)/i.test(a)?"":"px"},getDisplayType:function(a){a=a.tagName.toString().toLowerCase();return/^(b|big|i|small|tt|abbr|acronym|cite|code|dfn|em|kbd|strong|samp|var|a|bdo|br|img|map|object|q|script|span|sub|sup|button|input|label|select|textarea)$/i.test(a)?
"inline":/^(li)$/i.test(a)?"list-item":/^(tr)$/i.test(a)?"table-row":"block"},addClass:function(a,b){a.classList?a.classList.add(b):a.className+=(a.className.length?" ":"")+b},removeClass:function(a,b){a.classList?a.classList.remove(b):a.className=a.className.toString().replace(RegExp("(^|\\s)"+b.split(" ").join("|")+"(\\s|$)","gi")," ")}},getPropertyValue:function(c,b,g,h){function n(b,g){function c(){r&&a.setPropertyValue(b,"display","none")}var f=0;if(8>=E)f=t.css(b,g);else{var r=!1;if(/^(width|height)$/.test(g)&&
0===a.getPropertyValue(b,"display")&&(r=!0,a.setPropertyValue(b,"display",a.Values.getDisplayType(b))),!h){if("height"===g&&"border-box"!==a.getPropertyValue(b,"boxSizing").toString().toLowerCase())return f=b.offsetHeight-(parseFloat(a.getPropertyValue(b,"borderTopWidth"))||0)-(parseFloat(a.getPropertyValue(b,"borderBottomWidth"))||0)-(parseFloat(a.getPropertyValue(b,"paddingTop"))||0)-(parseFloat(a.getPropertyValue(b,"paddingBottom"))||0),c(),f;if("width"===g&&"border-box"!==a.getPropertyValue(b,
"boxSizing").toString().toLowerCase())return f=b.offsetWidth-(parseFloat(a.getPropertyValue(b,"borderLeftWidth"))||0)-(parseFloat(a.getPropertyValue(b,"borderRightWidth"))||0)-(parseFloat(a.getPropertyValue(b,"paddingLeft"))||0)-(parseFloat(a.getPropertyValue(b,"paddingRight"))||0),c(),f}f=l(b)===q?d.getComputedStyle(b,null):l(b).computedStyle?l(b).computedStyle:l(b).computedStyle=d.getComputedStyle(b,null);E&&"borderColor"===g&&(g="borderTopColor");f=9===E&&"filter"===g?f.getPropertyValue(g):f[g];
""!==f&&null!==f||(f=b.style[g]);c()}if("auto"===f&&/^(top|right|bottom|left)$/i.test(g)){var p=n(b,"position");("fixed"===p||"absolute"===p&&/top|left/i.test(g))&&(f=t(b).position()[g]+"px")}return f}var p;if(a.Hooks.registered[b]){var m=a.Hooks.getRoot(b);g===q&&(g=a.getPropertyValue(c,a.Names.prefixCheck(m)[0]));a.Normalizations.registered[m]&&(g=a.Normalizations.registered[m]("extract",c,g));p=a.Hooks.extractValue(b,g)}else a.Normalizations.registered[b]&&(g=a.Normalizations.registered[b]("name",
c),"transform"!==g&&(m=n(c,a.Names.prefixCheck(g)[0]),a.Values.isCSSNullValue(m)&&a.Hooks.templates[b]&&(m=a.Hooks.templates[b][1])),p=a.Normalizations.registered[b]("extract",c,m));return/^[\d-]/.test(p)||(p=l(c)&&l(c).isSVG&&a.Names.SVGAttribute(b)?/^(height|width)$/i.test(b)?c.getBBox()[b]:c.getAttribute(b):n(c,a.Names.prefixCheck(b)[0])),a.Values.isCSSNullValue(p)&&(p=0),2<=f.debug&&console.log("Get "+b+": "+p),p},setPropertyValue:function(c,b,g,h,n){var p=b;if("scroll"===b)n.container?n.container["scroll"+
n.direction]=g:"Left"===n.direction?d.scrollTo(g,n.alternateValue):d.scrollTo(n.alternateValue,g);else if(a.Normalizations.registered[b]&&"transform"===a.Normalizations.registered[b]("name",c))a.Normalizations.registered[b]("inject",c,g),p="transform",g=l(c).transformCache[b];else{a.Hooks.registered[b]&&(n=b,b=a.Hooks.getRoot(b),h=h||a.getPropertyValue(c,b),g=a.Hooks.injectValue(n,g,h));if(a.Normalizations.registered[b]&&(g=a.Normalizations.registered[b]("inject",c,g),b=a.Normalizations.registered[b]("name",
c)),p=a.Names.prefixCheck(b)[0],8>=E)try{c.style[p]=g}catch(t){f.debug&&console.log("Browser does not support ["+g+"] for ["+p+"]")}else l(c)&&l(c).isSVG&&a.Names.SVGAttribute(b)?c.setAttribute(b,g):c.style[p]=g;2<=f.debug&&console.log("Set "+b+" ("+p+"): "+g)}return[p,g]},flushTransformCache:function(c){function b(b){return parseFloat(a.getPropertyValue(c,b))}var g="";if((E||f.State.isAndroid&&!f.State.isChrome)&&l(c).isSVG){var h={translate:[b("translateX"),b("translateY")],skewX:[b("skewX")],skewY:[b("skewY")],
scale:1!==b("scale")?[b("scale"),b("scale")]:[b("scaleX"),b("scaleY")],rotate:[b("rotateZ"),0,0]};t.each(l(c).transformCache,function(a){/^translate/i.test(a)?a="translate":/^scale/i.test(a)?a="scale":/^rotate/i.test(a)&&(a="rotate");h[a]&&(g+=a+"("+h[a].join(" ")+") ",delete h[a])})}else{var n,p;t.each(l(c).transformCache,function(a){return n=l(c).transformCache[a],"transformPerspective"===a?(p=n,!0):(9===E&&"rotateZ"===a&&(a="rotate"),void(g+=a+n+" "))});p&&(g="perspective"+p+" "+g)}a.setPropertyValue(c,
"transform",g)}};a.Hooks.register();a.Normalizations.register();f.animate=function(){function c(){return g?J.promise||null:n}function b(){function e(){function g(a){var e=q,v=q,c=q;return h.isArray(a)?(e=a[0],!h.isArray(a[1])&&/^[\d-]/.test(a[1])||h.isFunction(a[1])?c=a[1]:(h.isString(a[1])||h.isArray(a[1]))&&(v=z(a[1],b.duration),a[2]!==q&&(c=a[2]))):e=a,v=v||b.easing,h.isFunction(e)&&(e=e.call(k,P,I)),h.isFunction(c)&&(c=c.call(k,P,I)),[e||0,v,c]}function n(e,k){var b,v;return v=(k||0).toString().toLowerCase().replace(/[%A-z]+$/,
function(a){return b=a,""}),b||(b=a.Values.getUnitType(e)),[v,b]}function M(){var e=k.parentNode,b=a.getPropertyValue(k,"position"),c=a.getPropertyValue(k,"fontSize"),g=b===v.lastPosition&&e===v.lastParent,L=c===v.lastFontSize&&e===v.lastParent;v.lastParent=e;v.lastPosition=b;v.lastFontSize=c;null===v.remToPx&&(v.remToPx=parseFloat(a.getPropertyValue(m.body,"fontSize"))||16);null===v.vwToPx&&(v.vwToPx=parseFloat(d.innerWidth)/100,v.vhToPx=parseFloat(d.innerHeight)/100);e={overflowX:null,overflowY:null,
boxSizing:null,width:null,minWidth:null,maxWidth:null,height:null,minHeight:null,maxHeight:null,paddingLeft:null};b={};if(b.remToPx=v.remToPx,b.vwToPx=v.vwToPx,b.vhToPx=v.vhToPx,E&&!l(k).isSVG)var h=/^auto$/i.test(k.currentStyle.width),n=/^auto$/i.test(k.currentStyle.height);g&&L||(l(k).isSVG||(e.overflowX=a.getPropertyValue(k,"overflowX"),e.overflowY=a.getPropertyValue(k,"overflowY"),e.boxSizing=a.getPropertyValue(k,"boxSizing"),e.minWidth=a.getPropertyValue(k,"minWidth"),e.maxWidth=a.getPropertyValue(k,
"maxWidth")||"none",e.minHeight=a.getPropertyValue(k,"minHeight"),e.maxHeight=a.getPropertyValue(k,"maxHeight")||"none",e.paddingLeft=a.getPropertyValue(k,"paddingLeft")),e.width=a.getPropertyValue(k,"width",null,!0),e.height=a.getPropertyValue(k,"height",null,!0));g?(b.percentToPxRatioWidth=v.lastPercentToPxWidth,b.percentToPxRatioHeight=v.lastPercentToPxHeight):(l(k).isSVG||(a.setPropertyValue(k,"overflowX","hidden"),a.setPropertyValue(k,"overflowY","hidden"),a.setPropertyValue(k,"boxSizing","content-box"),
a.setPropertyValue(k,"minWidth","10%"),a.setPropertyValue(k,"maxWidth","10%"),a.setPropertyValue(k,"minHeight","10%"),a.setPropertyValue(k,"maxHeight","10%")),a.setPropertyValue(k,"width","10%"),a.setPropertyValue(k,"height","10%"));L?b.emToPx=v.lastEmToPx:l(k).isSVG||a.setPropertyValue(k,"paddingLeft","10em");g||(b.percentToPxRatioWidth=v.lastPercentToPxWidth=(parseFloat(a.getPropertyValue(k,"width",null,!0))||1)/10,b.percentToPxRatioHeight=v.lastPercentToPxHeight=(parseFloat(a.getPropertyValue(k,
"height",null,!0))||1)/10);L||(b.emToPx=v.lastEmToPx=(parseFloat(a.getPropertyValue(k,"paddingLeft"))||1)/10);for(var s in e)null!==e[s]&&a.setPropertyValue(k,s,e[s]);return l(k).isSVG||(E?(h&&a.setPropertyValue(k,"width","auto"),n&&a.setPropertyValue(k,"height","auto")):(a.setPropertyValue(k,"height","auto"),e.height!==a.getPropertyValue(k,"height",null,!0)&&a.setPropertyValue(k,"height",e.height),a.setPropertyValue(k,"width","auto"),e.width!==a.getPropertyValue(k,"width",null,!0)&&a.setPropertyValue(k,
"width",e.width))),1<=f.debug&&console.log("Unit ratios: "+JSON.stringify(b),k),b}if(b.begin&&0===P)try{b.begin.call(p,p)}catch(r){setTimeout(function(){throw r;},1)}if("scroll"===H){var s,R,B,w=/^x$/i.test(b.axis)?"Left":"Top",x=parseFloat(b.offset)||0;b.container?b.container.jquery||h.isNode(b.container)?(b.container=b.container[0]||b.container,s=b.container["scroll"+w],B=s+t(k).position()[w.toLowerCase()]+x):b.container=null:(s=f.State.scrollAnchor[f.State["scrollProperty"+w]],R=f.State.scrollAnchor[f.State["scrollProperty"+
("Left"===w?"Top":"Left")]],B=t(k).offset()[w.toLowerCase()]+x);c={scroll:{rootPropertyValue:!1,startValue:s,currentValue:s,endValue:B,unitType:"",easing:b.easing,scrollData:{container:b.container,direction:w,alternateValue:R}},element:k}}else if("reverse"===H){if(!l(k).tweensContainer)return void t.dequeue(k,b.queue);"none"===l(k).opts.display&&(l(k).opts.display="block");"hidden"===l(k).opts.visibility&&(l(k).opts.visibility="visible");l(k).opts.loop=!1;l(k).opts.begin=null;l(k).opts.complete=null;
A.easing||delete b.easing;A.duration||delete b.duration;b=t.extend({},l(k).opts,b);var w=t.extend(!0,{},l(k).tweensContainer),C;for(C in w)"element"!==C&&(x=w[C].startValue,w[C].startValue=w[C].currentValue=w[C].endValue,w[C].endValue=x,A&&(w[C].easing=b.easing));c=w}else if("start"===H){l(k).tweensContainer&&!0===l(k).isAnimating&&(w=l(k).tweensContainer);for(x in u){B=g(u[x]);s=B[0];R=B[1];B=B[2];var x=a.Names.camelCase(x),F=a.Hooks.getRoot(x);C=!1;if(l(k).isSVG||!1!==a.Names.prefixCheck(F)[1]||
a.Normalizations.registered[F]!==q){(b.display&&"none"!==b.display||b.visibility&&"hidden"!==b.visibility)&&/opacity|filter/.test(x)&&!B&&0!==s&&(B=0);b._cacheValues&&w&&w[x]?(B===q&&(B=w[x].endValue+w[x].unitType),C=l(k).rootPropertyValueCache[F]):a.Hooks.registered[x]?B===q?(C=a.getPropertyValue(k,F),B=a.getPropertyValue(k,x,C)):C=a.Hooks.templates[F][1]:B===q&&(B=a.getPropertyValue(k,x));var y,N=!1;y=n(x,B);B=y[0];F=y[1];y=n(x,s);s=y[0].replace(/^([+-\/*])=/,function(a,e){return N=e,""});y=y[1];
B=parseFloat(B)||0;s=parseFloat(s)||0;var O;if("%"===y&&(/^(fontSize|lineHeight)$/.test(x)?(s/=100,y="em"):/^scale/.test(x)?(s/=100,y=""):/(Red|Green|Blue)$/i.test(x)&&(s=s/100*255,y="")),/[\/*]/.test(N))y=F;else if(F!==y&&0!==B)if(0===s)y=F;else{O=O||M();var Q=/margin|padding|left|right|width|text|word|letter/i.test(x)||/X$/.test(x)?"x":"y";switch(F){case "%":B*="x"===Q?O.percentToPxRatioWidth:O.percentToPxRatioHeight;break;case "px":break;default:B*=O[F+"ToPx"]}switch(y){case "%":B*=1/("x"===Q?
O.percentToPxRatioWidth:O.percentToPxRatioHeight);break;case "px":break;default:B*=1/O[y+"ToPx"]}}switch(N){case "+":s=B+s;break;case "-":s=B-s;break;case "*":s*=B;break;case "/":s=B/s}c[x]={rootPropertyValue:C,startValue:B,currentValue:B,endValue:s,unitType:y,easing:R};f.debug&&console.log("tweensContainer ("+x+"): "+JSON.stringify(c[x]),k)}else f.debug&&console.log("Skipping ["+F+"] due to a lack of browser support.")}c.element=k}c.element&&(a.Values.addClass(k,"animating"),L.push(c),l(k).tweensContainer=
c,l(k).opts=b,l(k).isAnimating=!0,P===I-1?(1E4<f.State.calls.length&&(f.State.calls=G(f.State.calls)),f.State.calls.push([L,p,b,null,J.resolver]),!1===f.State.isTicking&&(f.State.isTicking=!0,D())):P++)}var k=this,b=t.extend({},f.defaults,A),c={};if(l(k)===q&&t.data(k,F,{isSVG:h.isSVG(k),isAnimating:!1,computedStyle:null,tweensContainer:null,rootPropertyValueCache:{},transformCache:{}}),parseFloat(b.delay)&&!1!==b.queue&&t.queue(k,b.queue,function(a){f.velocityQueueEntryFlag=!0;l(k).delayTimer={setTimeout:setTimeout(a,
parseFloat(b.delay)),next:a}}),!0===f.mock)b.duration=1;else switch(b.duration.toString().toLowerCase()){case "fast":b.duration=200;break;case "normal":b.duration=y;break;case "slow":b.duration=600;break;default:b.duration=parseFloat(b.duration)||1}b.easing=z(b.easing,b.duration);b.begin&&!h.isFunction(b.begin)&&(b.begin=null);b.progress&&!h.isFunction(b.progress)&&(b.progress=null);b.complete&&!h.isFunction(b.complete)&&(b.complete=null);b.display&&(b.display=b.display.toString().toLowerCase(),"auto"===
b.display&&(b.display=f.CSS.Values.getDisplayType(k)));b.visibility&&(b.visibility=b.visibility.toString().toLowerCase());b.mobileHA=b.mobileHA&&f.State.isMobile&&!f.State.isGingerbread;!1===b.queue?b.delay?setTimeout(e,b.delay):e():t.queue(k,b.queue,function(a,k){return!0===k?(J.promise&&J.resolver(p),!0):(f.velocityQueueEntryFlag=!0,void e(a))});""!==b.queue&&"fx"!==b.queue||"inprogress"===t.queue(k)[0]||t.dequeue(k)}var g,n,s,p,u,A,x=arguments[0]&&(t.isPlainObject(arguments[0].properties)&&!arguments[0].properties.names||
h.isString(arguments[0].properties));if(h.isWrapped(this)?(g=!1,s=0,p=this,n=this):(g=!0,s=1,p=x?arguments[0].elements:arguments[0]),p=h.isWrapped(p)?[].slice.call(p):p){x?(u=arguments[0].properties,A=arguments[0].options):(u=arguments[s],A=arguments[s+1]);var I=h.isArray(p)||h.isNodeList(p)?p.length:1,P=0;if("stop"!==u&&!t.isPlainObject(A))for(A={},s+=1;s<arguments.length;s++)!h.isArray(arguments[s])&&/^\d/.test(arguments[s])?A.duration=parseFloat(arguments[s]):h.isString(arguments[s])||h.isArray(arguments[s])?
A.easing=arguments[s]:h.isFunction(arguments[s])&&(A.complete=arguments[s]);var J={promise:null,resolver:null,rejecter:null};g&&f.Promise&&(J.promise=new f.Promise(function(a,e){J.resolver=a;J.rejecter=e}));var H;switch(u){case "scroll":H="scroll";break;case "reverse":H="reverse";break;case "stop":t.each(h.isNode(p)?[p]:p,function(a,e){l(e)&&l(e).delayTimer&&(clearTimeout(l(e).delayTimer.setTimeout),l(e).delayTimer.next(),delete l(e).delayTimer)});var e=[];return t.each(f.State.calls,function(a,k){!1!==
k&&t.each(h.isNode(k[1])?[k[1]]:k[1],function(k,b){t.each(h.isNode(p)?[p]:p,function(k,v){if(v===b){if(l(v)&&t.each(l(v).tweensContainer,function(a,e){e.endValue=e.currentValue}),!0===A||h.isString(A)){var c=h.isString(A)?A:"";t.each(t.queue(v,c),function(a,e){h.isFunction(e)&&e(null,!0)});t.queue(v,c,[])}e.push(a)}})})}),t.each(e,function(a,e){C(e,!0)}),J.promise&&J.resolver(p),c();default:if(!t.isPlainObject(u)||t.isEmptyObject(u)){if(h.isString(u)&&f.Sequences[u]){var k=A.duration;return!0===A.backwards&&
(p=(p.jquery?[].slice.call(p):p).reverse()),t.each(p,function(a,e){parseFloat(A.stagger)?A.delay=parseFloat(A.stagger)*a:h.isFunction(A.stagger)&&(A.delay=A.stagger.call(e,a,I));A.drag&&(A.duration=parseFloat(k)||(/^(callout|transition)/.test(u)?1E3:y),A.duration=Math.max(A.duration*(A.backwards?1-a/I:(a+1)/I),0.75*A.duration,200));f.Sequences[u].call(e,e,A||{},a,I,p,J.promise?J:q)}),c()}s="Velocity: First argument ("+u+") was not a property map, a known action, or a registered sequence. Aborting.";
return J.promise?J.rejecter(Error(s)):console.log(s),c()}H="start"}var v={lastParent:null,lastPosition:null,lastFontSize:null,lastPercentToPxWidth:null,lastPercentToPxHeight:null,lastEmToPx:null,remToPx:null,vwToPx:null,vhToPx:null},L=[];t.each(h.isNode(p)?[p]:p,function(a,e){h.isNode(e)&&b.call(e)});x=t.extend({},f.defaults,A);if(x.loop=parseInt(x.loop),s=2*x.loop-1,x.loop)for(var M=0;s>M;M++){var B={delay:x.delay};x.complete&&M===s-1&&(B.complete=x.complete);f.animate(p,"reverse",B)}return c()}};
(c=d.jQuery||d.Zepto)&&(c.fn.velocity=f.animate,c.fn.velocity.defaults=f.defaults);"undefined"!=typeof define&&define.amd?define(function(){return f}):"undefined"!=typeof module&&module.exports&&(module.exports=f);t.each(["Down","Up"],function(a,b){f.Sequences["slide"+b]=function(a,c){var h=t.extend({},c),n={height:null,marginTop:null,marginBottom:null,paddingTop:null,paddingBottom:null,overflow:null,overflowX:null,overflowY:null},s=h.begin,d=h.complete,r=!1;null!==h.display&&(h.display="Down"===
b?h.display||"auto":h.display||"none");h.begin=function(){function c(){n.height=parseFloat(f.CSS.getPropertyValue(a,"height"));a.style.height="auto";f.CSS.getPropertyValue(a,"height")===n.height&&(r=!0);f.CSS.setPropertyValue(a,"height",n.height+"px")}if("Down"===b){n.overflow=[f.CSS.getPropertyValue(a,"overflow"),0];n.overflowX=[f.CSS.getPropertyValue(a,"overflowX"),0];n.overflowY=[f.CSS.getPropertyValue(a,"overflowY"),0];a.style.overflow="hidden";a.style.overflowX="visible";a.style.overflowY="hidden";
c();for(var h in n)if(!/^overflow/.test(h)){var d=f.CSS.getPropertyValue(a,h);"height"===h&&(d=parseFloat(d));n[h]=[d,0]}}else{c();for(h in n)d=f.CSS.getPropertyValue(a,h),"height"===h&&(d=parseFloat(d)),n[h]=[0,d];a.style.overflow="hidden";a.style.overflowX="visible";a.style.overflowY="hidden"}s&&s.call(a,a)};h.complete=function(a){var c="Down"===b?0:1;!0===r?n.height[c]="auto":n.height[c]+="px";for(var g in n)a.style[g]=n[g][c];d&&d.call(a,a)};f.animate(a,n,h)}});t.each(["In","Out"],function(a,
b){f.Sequences["fade"+b]=function(a,c,h,n){a=t.extend({},c);c={opacity:"In"===b?1:0};h!==n-1&&(a.complete=a.begin=null);null!==a.display&&(a.display=a.display||("In"===b?"auto":"none"));f.animate(this,c,a)}})}(window.jQuery||window.Zepto||window,window,document);
(function(c){var d,m,q,G;c.extend({zoommap:{init:function(){d=c(".zoom-map");m=c(window);q=c("html");G=q.hasClass("touch")?!0:!1;d.each(function(){var d=c(this),l=d.find(".zoom-map--label"),m=d.find(".zoom-map--outer");d.find(".zoom-map--image");var d=d.find(".zoom-map--poi"),q=m.width()*d.data("offset-x")||0,m=m.height()*d.data("offset-y")-(10-10*d.data("offset-y"))||0;d.css({left:q,top:m});l.css({left:30,top:30})});if(700<m.width()&&!q.hasClass("ie9"))d.on("click",l)},zoomIn:function(c){z(c)},zoomOut:function(c){u(c)}}});
var l=function(d){if(!G&&!1===c("html").hasClass("ie8")){var l=c(this);d.preventDefault();l.hasClass("zoomed-in")?u(l):z(l);return!1}},u=function(d){var l=c(d);if(!l.hasClass("animating")){l.addClass("animating");var m=l.find(".zoom-map--image");d=l.find(".zoom-map--label");var q=l.find(".zoom-map--poi");l.addClass("zoomed-out").removeClass("zoomed-in");d.velocity("fadeOut",{duration:300,complete:function(){m.velocity({top:"0",left:"0"},1200,function(){q.velocity("fadeIn",{duration:300});l.removeClass("animating")});
m.css({"-webkit-transform":"scale(1.2)","-moz-transform":"scale(1.2)","-ms-transform":"scale(1.2)","-o-transform":"scale(1.2)",transform:"scale(1.2)"},1200)}})}},z=function(d){var l=c(d);if(!l.hasClass("animating")){l.addClass("animating");var m=l.find(".zoom-map--image"),q=l.find(".zoom-map--label");d=l.find(".zoom-map--outer");var u=l.find(".zoom-map--poi");l.addClass("zoomed-in").removeClass("zoomed-out");var z=m.data("zoom-x")||0,n=m.data("zoom-y")||0,s=0.5*d.width()-q.width()/2,h=0.5*d.height()-
7;u.velocity("fadeOut",{duration:300,complete:function(){q.css({left:s,top:h});m.velocity({left:z,top:n},1200,function(){q.velocity("fadeIn",{duration:300,complete:function(){l.removeClass("animating")}})});m.css({"-webkit-transform":"scale(4.2)","-moz-transform":"scale(4.2)","-ms-transform":"scale(4.2)","-o-transform":"scale(4.2)",transform:"scale(4.2)"})}})}}})(jQuery);$(document).ready($.zoommap.init);
$().ready(function(){$(window).on("TNZ.HeroVideo.FullscreenOn",function(c){if($("body").hasClass("full-screen")){var d=$(".custom-side-deal");d.css({marginTop:90});$(window).on("scroll",function(){var c=90+$(window).scrollTop();0>c?d.css({marginTop:c}):d.css({marginTop:0})}).scroll()}else d=$(".page-headerblock").find("aside"),d.css({marginTop:"0"})})});TNZ=window.TNZ||{};TNZ.MapDefaultConfig=TNZ.MapDefaultConfig||{};TNZ.MapDefaultConfig.desktop=1;TNZ.MapDefaultConfig.tablet=2;
TNZ.MapDefaultConfig.mobile=3;TNZ.MapDefaultConfig.spritesheetFile=TNZ.initialRequestConfig.staticDomain+"/visit/alacrity/images/map/markers/map-icons.png?"+TNZ.initialRequestConfig.appVersion;TNZ.MapDefaultConfig.iconshadowFile=TNZ.initialRequestConfig.staticDomain+"/visit/alacrity/images/map/markers/shadow.png?"+TNZ.initialRequestConfig.appVersion;TNZ.MapDefaultConfig.icons="default garden island cycling fishing hiking beach skytower hobbiton volcano winery maori boating museum golf accommodation heart".split(" ");
TNZ.MapDefaultConfig.iconLookup=function(){for(var c={},d=TNZ.MapDefaultConfig.icons.length;d--;)c[TNZ.MapDefaultConfig.icons[d]]=d;return c};TNZ.MapDefaultConfig.metaPOIIcons={airport:{width:15,height:15,posX:90,posY:0},river:{width:15,height:15,posX:90,posY:15},town:{width:40,height:40,posX:112,posY:0}};TNZ.MapDefaultConfig.iconStateTypeLookup={normal:0,hover:1,selected:2};
TNZ.MapDefaultConfig.getIconImage=function(c,d){var m=TNZ.MapDefaultConfig.getIconStateType(c),q=TNZ.MapDefaultConfig.lookupIconPos(d);return{url:TNZ.MapDefaultConfig.spritesheetFile,origin:new google.maps.Point(30*m,40*q),size:new google.maps.Size(30,40)}};TNZ.MapDefaultConfig.lookupIconPos=function(c){var d=TNZ.MapDefaultConfig.iconLookup();return d[c]||d["default"]};TNZ.MapDefaultConfig.getPOIIconMeta=function(c){return TNZ.MapDefaultConfig.metaPOIIcons[c]};
TNZ.MapDefaultConfig.getIconStateType=function(c){return TNZ.MapDefaultConfig.iconStateTypeLookup[c]||0};
TNZ.MapDefaultConfig.defaultThresholdSettingArray=[{styles:[{featureType:"poi",elementType:"all",stylers:[{hue:"#b1d093"},{saturation:0},{lightness:70},{visibility:"on"}]},{featureType:"administrative",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"road",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"transit",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"landscape",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"landscape.natural",elementType:"all",
stylers:[{hue:"#ffffff"},{saturation:-100},{lightness:100},{visibility:"on"}]},{featureType:"landscape.natural.terrain",stylers:[{hue:"#000000"},{saturation:-5},{lightness:-10},{visibility:"on"}]},{featureType:"landscape",elementType:"labels",stylers:[{visibility:"off"}]},{featureType:"water",elementType:"labels",stylers:[{visibility:"off"}]},{featureType:"poi",elementType:"labels",stylers:[{visibility:"off"}]},{featureType:"water",elementType:"geometry",stylers:[{hue:"#7cb3d9"},{saturation:-20},
{lightness:5},{visibility:"on"}]},{featureType:"road.highway",elementType:"geometry",stylers:[{visibility:"off"}]},{featureType:"road.highway",elementType:"labels",stylers:[{hue:"#fb9d24"},{saturation:-5},{lightness:-10},{visibility:"off"}]}],meta_poi_visible:!1,meta_object_visible:!0},{styles:[{featureType:"poi",elementType:"all",stylers:[{hue:"#b1d093"},{saturation:0},{lightness:70},{visibility:"on"}]},{featureType:"administrative",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"road",
elementType:"all",stylers:[{visibility:"off"}]},{featureType:"transit",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"landscape",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"landscape.natural",elementType:"all",stylers:[{hue:"#ffffff"},{saturation:-100},{lightness:100},{visibility:"on"}]},{featureType:"landscape.natural.terrain",stylers:[{hue:"#000000"},{saturation:-5},{lightness:-10},{visibility:"on"}]},{featureType:"landscape",elementType:"labels",stylers:[{visibility:"off"}]},
{featureType:"water",elementType:"labels",stylers:[{visibility:"off"}]},{featureType:"poi",elementType:"labels",stylers:[{visibility:"off"}]},{featureType:"water",elementType:"geometry",stylers:[{hue:"#7cb3d9"},{saturation:-20},{lightness:5},{visibility:"on"}]},{featureType:"road.highway",elementType:"geometry",stylers:[{hue:"#cccccc"},{saturation:-100},{lightness:75},{visibility:"on"}]},{featureType:"road.highway",elementType:"labels",stylers:[{hue:"#fb9d24"},{saturation:-5},{lightness:-10},{visibility:"off"}]}],
meta_poi_visible:!0,meta_object_visible:!1},{styles:[{featureType:"poi",elementType:"all",stylers:[{hue:"#b1d093"},{saturation:0},{lightness:70},{visibility:"on"}]},{featureType:"administrative",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"road",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"transit",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"landscape",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"landscape.natural",elementType:"all",
stylers:[{hue:"#ffffff"},{saturation:-100},{lightness:100},{visibility:"on"}]},{featureType:"landscape.natural.terrain",stylers:[{hue:"#000000"},{saturation:-5},{lightness:-10},{visibility:"on"}]},{featureType:"landscape",elementType:"labels",stylers:[{visibility:"off"}]},{featureType:"water",elementType:"labels",stylers:[{visibility:"off"}]},{featureType:"poi",elementType:"labels",stylers:[{visibility:"off"}]},{featureType:"water",elementType:"geometry",stylers:[{hue:"#7cb3d9"},{saturation:-20},
{lightness:5},{visibility:"on"}]},{featureType:"road.highway",elementType:"geometry",stylers:[{hue:"#cccccc"},{saturation:-100},{lightness:75},{visibility:"on"}]},{featureType:"road.highway",elementType:"labels",stylers:[{hue:"#fb9d24"},{saturation:-5},{lightness:-10},{visibility:"on"}]}],meta_poi_visible:!0,meta_object_visible:!1}];TNZ.MapDefaultConfig.getStyleThresholdSettingArray=function(){return aDefaultThresholdSettingArray_};Modules=window.Modules||{};Modules.Gmap=null;
(function(c){var d,m=[],q=[],G=[],l=null,u=!0,z=null,D,C,F,y,H,E;c.extend({gmap:{init:function(){C=TNZ.MapDefaultConfig.iconshadowFile;F="getMapInfoWindow";y=TNZ.initialRequestConfig.staticDomain+"/visit/alacrity/js/modules/gmap/overlay.infocard.js?"+TNZ.initialRequestConfig.appVersion;H=TNZ.initialRequestConfig.staticDomain+"/visit/alacrity/js/modules/gmap/overlay.label.js?"+TNZ.initialRequestConfig.appVersion;E=TNZ.MapDefaultConfig.defaultThresholdSettingArray;D=1;c(document).on("click touchstart",
"div.mapinfo-close a",c.gmap.unselectMarkers);c(document).on("click touchstart","div.module-gmap-welcome-panel div.mapinfo-close a",c.gmap.removeWelcomeMsg);c(document).one("click touchstart","div.module-gmap-wrapper",c.gmap.removeWelcomeMsg);_setBreakpointByDevice();c.gmap.loadMap()},loadMap:function(){TNZ.Map.ready(function(){d=new TNZ.Map("div.module-gmap-wrapper",{hideRegionLabels:!0,thresholdArray:[10,12]});google.maps.visualRefresh=!0;var n={styles:_getCustomStyles(),maxZoom:12,keyboardShortcuts:!1,
mapTypeControl:!1,overviewMapControl:!1,panControl:!1,scaleControl:!1,streetViewControl:!1,rotateControl:!1,scrollwheel:!1,zoomControl:!0,zoomControlOptions:{position:google.maps.ControlPosition.TOP_RIGHT}};d.setOptions(n);l=new google.maps.LatLngBounds;google.maps.event.addListener(d.getGoogleMap(),"zoom_changed",_onMapZoomChange);$LAB.script(y).script(H).wait(function(){c.gmap.loadPOIOnMap();c.gmap.afterLoadMap()})})},loadPOIOnMap:function(){TNZ.Map.ready(function(){c("div.js-module-gmap-meta span.poi-marker").each(function(){var n=
c(this).data();c.gmap.addActivityMarker(n.map_lat,n.map_lng,{icon_name_key:n.map_icon,unique_id:n.unique_id,show_info_window:!0})});var n=[];c("div.js-module-gmap-meta span.poi-region").each(function(){var d=c(this).data();"-1"==c.inArray(d.region_keyword_unique_id,n)&&n.push(d.region_keyword_unique_id)});c.ajax({url:"/_proxy/data_16h/region/detailbykeyword.cfm",data:{unique_id:n.join(",")},type:"GET",error:function(c,h){},success:function(n){for(var h=0;h<n.metadata.unique_id.length;h++){var d=n.value[n.metadata.unique_id[h]];
c.gmap.addTownMarker(d.latitude,d.longitude,{label:d.label,unique_id:n.value[n.metadata.unique_id[h]],name_key:d.name_key});c.gmap.addLabel(d.latitude,d.longitude,d.label,d.name_key)}}});c.gmap.recalculateBounds()})},afterLoadMap:function(){_showMapLoader(!1);_showMapWelcomeMsg();c(window).trigger("TNZ.Module.GMap.loaded")},addActivityMarker:function(n,l,h){h="undefined"!==typeof h?h:{unique_id:-1,icon_name_key:"default",show_info_window:!1};h.unique_id=h.unique_id||"-1";h.icon_name_key=h.icon_name_key||
"default";h.show_info_window=h.show_info_window||!1;var t=h.icon_name_key,f=new google.maps.LatLng(n,l),q=TNZ.MapDefaultConfig.getIconImage("normal",t);n=new google.maps.MarkerImage(C,new google.maps.Size(47,43),new google.maps.Point(0,0),new google.maps.Point(14,40));var y=new google.maps.Marker({position:f,icon:q,shadow:n,zIndex:200,selected:!1,iconnamekey:h.icon_name_key,uniqueid:h.unique_id});"undefined"!==h.unique_id&&(google.maps.event.addListener(y,"click",function(){_removeInfoPopup();c.gmap.unselectMarkers();
h.show_info_window&&(z=new Modules.Gmap.InfoCardDefault(f,h.unique_id,d.getCanvas(),F,u),z.setMap(y.getMap()));u=!1;q=TNZ.MapDefaultConfig.getIconImage("selected",t);y.setIcon(q);y.selected=!0;y.setAnimation(google.maps.Animation.BOUNCE)}),google.maps.event.addListener(y,"mouseout",function(){y.selected||(q=TNZ.MapDefaultConfig.getIconImage("normal",t),y.setIcon(q))}),google.maps.event.addListener(y,"mouseover",function(){y.selected||(q=TNZ.MapDefaultConfig.getIconImage("hover",t),y.setIcon(q))}));
y.setMap(d.getGoogleMap());m.push(y)},removeActivityMarker:function(c){for(var d=0;d<m.length;d++)if(m[d].uniqueid==c){m[d].setMap(null);m.splice(d,1);break}},clearActivityMarkers:function(){for(var c=0;c<m.length;c++)m[c].setMap(null);m.splice(c,1)},addTownMarker:function(c,l,h){h="undefined"!==typeof h?h:{};h.unique_id=h.unique_id||"-1";h.label=h.label||"";h.name_key=h.name_key||"";h.show_info_window=h.show_info_window||!1;var m=new google.maps.LatLng(c,l);c={url:TNZ.MapDefaultConfig.spritesheetFile,
origin:new google.maps.Point(112,0),anchor:new google.maps.Point(21,21),size:new google.maps.Size(40,40)};var f=new google.maps.Marker({position:m,icon:c,zIndex:100});-1!=h.unique_id&&google.maps.event.addListener(f,"click",function(){if(2==D||3==D){var c=new google.maps.InfoWindow({zIndex:6E3});c.setContent("\x3ca href\x3d'"+TNZ.initialRequestConfig.baseURL+"/"+h.name_key+"/'\x3e"+h.label+"\x3c/a\x3e");c.open(d.getGoogleMap(),f)}else _removeInfoPopup(),h.show_info_window&&(z=new Modules.Gmap.InfoCardDefault(m,
h.unique_id,d.getCanvas(),F,u),z.setMap(f.getMap())),u=!1});f.setMap(d.getGoogleMap());q.push(f)},removeTownMarker:function(c){for(var d=0;d<q.length;d++)if(q[d].uniqueid==c){q[d].setMap(null);q.splice(d,1);break}},addLabel:function(c,l,h,m){c=new google.maps.LatLng(c,l);l={customcssclass:"gmap-label gmap-label-"+h.toLowerCase().replace(/ /g,"-")};h=new Modules.Gmap.LabelMarkerDefault(c,h.toUpperCase(),"/"+TNZ.initialRequestConfig.marketFolder+"/"+m,l);G.push(h);h.setMap(d.getGoogleMap())},getAllActMarkerObjects:function(){return m},
getAllTownMarkerObjects:function(){return q},getAllLabelObjects:function(){return G},getCurrentSelectedMarker:function(){for(var c=0;c<m.length;c++)if(m[c].selected)return m[c]},getCurrentMapObj:function(){return d},unselectMarkers:function(){for(var c=0;c<m.length;c++){m[c].selected=!1;var d=TNZ.MapDefaultConfig.getIconImage("normal",m[c].iconnamekey);m[c].setIcon(d);m[c].setAnimation(null)}},recalculateBounds:function(){l=new google.maps.LatLngBounds;if(m.length){for(var n=0;n<m.length;n++)c.gmap.extendBound(m[n].position);
c.gmap.fitBounds()}else d.setCenter({latitude:TNZ.Map.DEFAULT_CENTRE.lat,longitude:TNZ.Map.DEFAULT_CENTRE.lng}),d.setZoom(6)},recalculateBoundsByLatLngArray:function(d){l=new google.maps.LatLngBounds;for(var m=0;m<d.length;m++){var h=new google.maps.LatLng(d[m].lat,d[m].lng);l.extend(h)}c.gmap.fitBounds()},removeWelcomeMsg:function(){c("div.module-gmap-welcome-panel").fadeOut("fast")},resizeMap:function(){google.maps.event.trigger(d.getGoogleMap(),"resize")},getCenter:function(){return d.getCenter()},
getBreakpoint:function(){var d=c(window).outerWidth(),l,h={phones:{min:0,max:480},phones_small_tablets:{min:481,max:767},tablets:{min:768,max:979},desktop:{min:980,max:1199},large:{min:1200}},m;for(m in h){var f=-1,q=-1,f=h[m].min;void 0!=h[m].max&&(q=h[m].max);-1!=q&&d>=f&&d<=q?l=m:!l&&-1==q&&d>=q&&(l=m)}return l},getMapBound:function(){return l},fitBounds:function(){d.fitBounds(l)},extendBound:function(c){l.extend(c)}}});_setBreakpointByDevice=function(){var d=c.gmap.getBreakpoint();D=1;D="tablets"==
d||"phones_small_tablets"==d?2:"phones"==d?3:1};_removeInfoPopup=function(){z&&(z.setMap(null),z=null)};_getCustomStyles=function(){var c=E[1].styles,d;for(d in c)if("road"==c[d].featureType){c[d].stylers[0].visibility="on";break}return c};_showMapLoader=function(d){d?c("div.module-gmap-wrapper").addClass("loading"):c("div.module-gmap-wrapper").removeClass("loading")};_onMapZoomChange=function(){};_showMapWelcomeMsg=function(){2!=D&&1!=D||c("div.module-gmap-welcome-panel").show()}})(jQuery);$(document).ready($.gmap.init);
(function(c){var d,m,q,G,l,u,z,D,C,F,y,H,E;c.extend({embedherovideo:{init:function(){d=c(window);m=c("body");q=c("html");G=c(".hero--video");l=G.find(".hero--video--wrap");u=G.find(".hero--video--content");G.find(".hero--video--meta");z=c("#video");D=c(".hero-image");F=G.find(".hero--video--arrow");C=c("#global-header");y=u.data("title-offset-x");H=u.data("title-offset-y");z.height();E=C.height();a();F.click(function(a){a.preventDefault();a=G.position().top+G.height()-C.height()+(C.data("sticky-offset")||
55);c("html,body").animate({scrollTop:a},1E3)});q.hasClass("ie8")||q.hasClass("ie9")||q.hasClass("touch")?(z.remove(),z=c([]),D.css({opacity:"1",display:"block"}),s(),t(),h(),f()):n();d.on("resize",_.debounce(function(){a();s();t()},400))}}});var n=function(){var a=_.once(function(a){l.addClass("stuck")});d.on("scroll",function(){var b=d.scrollTop();b>=C.data("sticky-offset")&&a(b)});z.length?x():(D.css({opacity:"1",display:"block"}),s(),f());h()},s=function(){m.hasClass("full-screen")?G.height(d.height()-
E):G.height("auto")},h=function(){u.find("h1").css({left:y+"%",top:H+"%"});u.find("h1,a").css({opacity:1})},t=function(){var a=700<d.width()?!0:!1,b=0==z.length?D:z,c=0;G.hasClass("embedHeroVideoRight")?c=b.width()-d.width():G.hasClass("embedHeroVideoCentre")&&(c=(b.width()-d.width())/2);D.css({left:"-"+c+"px"});a&&0!=z.length&&(z.css({display:"block"}),z.css({"margin-left":"-"+c+"px"}))},f=function(){D.addClass("zooming")},x=function(){var a=!1;z.bind("ended",function(a){I(a)});z.bind("loadedmetadata play loadeddata",
function(b){a||(s(),t(),a=!0)})},I=function(a){m.hasClass("full-screen")?D.show(10,function(){z.fadeOut(400,function(){z.remove();z=c([])})}):(z.css({opacity:"0",display:"none"}).remove(),z=c([]),D.css({opacity:"1",display:"block"}));f()},a=function(){var a=d.width()/d.height();!q.hasClass("touch")&&1.2<a?(m.addClass("full-screen"),d.trigger("TNZ.HeroVideo.FullscreenOn")):(m.removeClass("full-screen"),d.trigger("TNZ.HeroVideo.FullscreenOff"))}})(jQuery);$(document).ready($.embedherovideo.init);
(function(){var c=this,d=c._,m={},q=Array.prototype,G=Object.prototype,l=q.push,u=q.slice,z=q.concat,D=G.toString,C=G.hasOwnProperty,F=q.forEach,y=q.map,H=q.reduce,E=q.reduceRight,n=q.filter,s=q.every,h=q.some,t=q.indexOf,f=q.lastIndexOf,G=Array.isArray,x=Object.keys,I=Function.prototype.bind,a=function(e){return e instanceof a?e:this instanceof a?(this._wrapped=e,void 0):new a(e)};"undefined"!=typeof exports?("undefined"!=typeof module&&module.exports&&(exports=module.exports=a),exports._=a):c._=
a;a.VERSION="1.4.4";var r=a.each=a.forEach=function(e,k,b){if(null!=e)if(F&&e.forEach===F)e.forEach(k,b);else if(e.length===+e.length)for(var c=0,d=e.length;d>c&&k.call(b,e[c],c,e)!==m;c++);else for(c in e)if(a.has(e,c)&&k.call(b,e[c],c,e)===m)break};a.map=a.collect=function(a,k,b){var c=[];return null==a?c:y&&a.map===y?a.map(k,b):(r(a,function(a,e,d){c[c.length]=k.call(b,a,e,d)}),c)};a.reduce=a.foldl=a.inject=function(e,k,b,c){var d=2<arguments.length;if(null==e&&(e=[]),H&&e.reduce===H)return c&&
(k=a.bind(k,c)),d?e.reduce(k,b):e.reduce(k);if(r(e,function(a,e,f){d?b=k.call(c,b,a,e,f):(b=a,d=!0)}),!d)throw new TypeError("Reduce of empty array with no initial value");return b};a.reduceRight=a.foldr=function(e,k,b,c){var d=2<arguments.length;if(null==e&&(e=[]),E&&e.reduceRight===E)return c&&(k=a.bind(k,c)),d?e.reduceRight(k,b):e.reduceRight(k);var f=e.length;if(f!==+f)var g=a.keys(e),f=g.length;if(r(e,function(a,h,l){h=g?g[--f]:--f;d?b=k.call(c,b,e[h],h,l):(b=e[h],d=!0)}),!d)throw new TypeError("Reduce of empty array with no initial value");
return b};a.find=a.detect=function(a,k,c){var d;return b(a,function(a,e,b){return k.call(c,a,e,b)?(d=a,!0):void 0}),d};a.filter=a.select=function(a,k,b){var c=[];return null==a?c:n&&a.filter===n?a.filter(k,b):(r(a,function(a,e,d){k.call(b,a,e,d)&&(c[c.length]=a)}),c)};a.reject=function(e,k,b){return a.filter(e,function(a,e,c){return!k.call(b,a,e,c)},b)};a.every=a.all=function(e,k,b){k||(k=a.identity);var c=!0;return null==e?c:s&&e.every===s?e.every(k,b):(r(e,function(a,e,d){return(c=c&&k.call(b,a,
e,d))?void 0:m}),!!c)};var b=a.some=a.any=function(e,k,b){k||(k=a.identity);var c=!1;return null==e?c:h&&e.some===h?e.some(k,b):(r(e,function(a,e,d){return c||(c=k.call(b,a,e,d))?m:void 0}),!!c)};a.contains=a.include=function(a,k){return null==a?!1:t&&a.indexOf===t?-1!=a.indexOf(k):b(a,function(a){return a===k})};a.invoke=function(e,k){var b=u.call(arguments,2),c=a.isFunction(k);return a.map(e,function(a){return(c?k:a[k]).apply(a,b)})};a.pluck=function(e,k){return a.map(e,function(a){return a[k]})};
a.where=function(e,k,b){return a.isEmpty(k)?b?null:[]:a[b?"find":"filter"](e,function(a){for(var e in k)if(k[e]!==a[e])return!1;return!0})};a.findWhere=function(e,k){return a.where(e,k,!0)};a.max=function(e,k,b){if(!k&&a.isArray(e)&&e[0]===+e[0]&&65535>e.length)return Math.max.apply(Math,e);if(!k&&a.isEmpty(e))return-1/0;var c={computed:-1/0,value:-1/0};return r(e,function(a,e,d){e=k?k.call(b,a,e,d):a;e>=c.computed&&(c={value:a,computed:e})}),c.value};a.min=function(e,k,b){if(!k&&a.isArray(e)&&e[0]===
+e[0]&&65535>e.length)return Math.min.apply(Math,e);if(!k&&a.isEmpty(e))return 1/0;var c={computed:1/0,value:1/0};return r(e,function(a,e,d){e=k?k.call(b,a,e,d):a;c.computed>e&&(c={value:a,computed:e})}),c.value};a.shuffle=function(e){var k,b=0,c=[];return r(e,function(e){k=a.random(b++);c[b-1]=c[k];c[k]=e}),c};var g=function(e){return a.isFunction(e)?e:function(a){return a[e]}};a.sortBy=function(e,k,b){var c=g(k);return a.pluck(a.map(e,function(a,e,k){return{value:a,index:e,criteria:c.call(b,a,e,
k)}}).sort(function(a,e){var k=a.criteria,b=e.criteria;if(k!==b){if(k>b||void 0===k)return 1;if(b>k||void 0===b)return-1}return a.index<e.index?-1:1}),"value")};var N=function(e,k,b,c){var d={},f=g(k||a.identity);return r(e,function(a,k){var g=f.call(b,a,k,e);c(d,g,a)}),d};a.groupBy=function(e,k,b){return N(e,k,b,function(e,b,k){(a.has(e,b)?e[b]:e[b]=[]).push(k)})};a.countBy=function(e,b,c){return N(e,b,c,function(e,b){a.has(e,b)||(e[b]=0);e[b]++})};a.sortedIndex=function(e,b,c,d){c=null==c?a.identity:
g(c);b=c.call(d,b);for(var f=0,h=e.length;h>f;){var l=f+h>>>1;b>c.call(d,e[l])?f=l+1:h=l}return f};a.toArray=function(e){return e?a.isArray(e)?u.call(e):e.length===+e.length?a.map(e,a.identity):a.values(e):[]};a.size=function(e){return null==e?0:e.length===+e.length?e.length:a.keys(e).length};a.first=a.head=a.take=function(a,b,c){return null==a?void 0:null==b||c?a[0]:u.call(a,0,b)};a.initial=function(a,b,c){return u.call(a,0,a.length-(null==b||c?1:b))};a.last=function(a,b,c){return null==a?void 0:
null==b||c?a[a.length-1]:u.call(a,Math.max(a.length-b,0))};a.rest=a.tail=a.drop=function(a,b,c){return u.call(a,null==b||c?1:b)};a.compact=function(e){return a.filter(e,a.identity)};var w=function(e,b,c){return r(e,function(e){a.isArray(e)?b?l.apply(c,e):w(e,b,c):c.push(e)}),c};a.flatten=function(a,b){return w(a,b,[])};a.without=function(e){return a.difference(e,u.call(arguments,1))};a.uniq=a.unique=function(e,b,c,d){a.isFunction(b)&&(d=c,c=b,b=!1);c=c?a.map(e,c,d):e;var f=[],g=[];return r(c,function(c,
d){(b?d&&g[g.length-1]===c:a.contains(g,c))||(g.push(c),f.push(e[d]))}),f};a.union=function(){return a.uniq(z.apply(q,arguments))};a.intersection=function(e){var b=u.call(arguments,1);return a.filter(a.uniq(e),function(e){return a.every(b,function(b){return 0<=a.indexOf(b,e)})})};a.difference=function(e){var b=z.apply(q,u.call(arguments,1));return a.filter(e,function(e){return!a.contains(b,e)})};a.zip=function(){for(var e=u.call(arguments),b=a.max(a.pluck(e,"length")),c=Array(b),d=0;b>d;d++)c[d]=
a.pluck(e,""+d);return c};a.object=function(a,b){if(null==a)return{};for(var c={},d=0,f=a.length;f>d;d++)b?c[a[d]]=b[d]:c[a[d][0]]=a[d][1];return c};a.indexOf=function(e,b,c){if(null==e)return-1;var d=0,f=e.length;if(c){if("number"!=typeof c)return d=a.sortedIndex(e,b),e[d]===b?d:-1;d=0>c?Math.max(0,f+c):c}if(t&&e.indexOf===t)return e.indexOf(b,c);for(;f>d;d++)if(e[d]===b)return d;return-1};a.lastIndexOf=function(a,b,c){if(null==a)return-1;var d=null!=c;if(f&&a.lastIndexOf===f)return d?a.lastIndexOf(b,
c):a.lastIndexOf(b);for(c=d?c:a.length;c--;)if(a[c]===b)return c;return-1};a.range=function(a,b,c){1>=arguments.length&&(b=a||0,a=0);c=arguments[2]||1;for(var d=Math.max(Math.ceil((b-a)/c),0),f=0,g=Array(d);d>f;)g[f++]=a,a+=c;return g};a.bind=function(a,b){if(a.bind===I&&I)return I.apply(a,u.call(arguments,1));var c=u.call(arguments,2);return function(){return a.apply(b,c.concat(u.call(arguments)))}};a.partial=function(a){var b=u.call(arguments,1);return function(){return a.apply(this,b.concat(u.call(arguments)))}};
a.bindAll=function(e){var b=u.call(arguments,1);return 0===b.length&&(b=a.functions(e)),r(b,function(b){e[b]=a.bind(e[b],e)}),e};a.memoize=function(e,b){var c={};return b||(b=a.identity),function(){var d=b.apply(this,arguments);return a.has(c,d)?c[d]:c[d]=e.apply(this,arguments)}};a.delay=function(a,b){var c=u.call(arguments,2);return setTimeout(function(){return a.apply(null,c)},b)};a.defer=function(b){return a.delay.apply(a,[b,1].concat(u.call(arguments,1)))};a.throttle=function(a,b){var c,d,f,
g,h=0,l=function(){h=new Date;f=null;g=a.apply(c,d)};return function(){var m=new Date,n=b-(m-h);return c=this,d=arguments,0>=n?(clearTimeout(f),f=null,h=m,g=a.apply(c,d)):f||(f=setTimeout(l,n)),g}};a.debounce=function(a,b,c){var d,f;return function(){var g=this,h=arguments,l=c&&!d;return clearTimeout(d),d=setTimeout(function(){d=null;c||(f=a.apply(g,h))},b),l&&(f=a.apply(g,h)),f}};a.once=function(a){var b,c=!1;return function(){return c?b:(c=!0,b=a.apply(this,arguments),a=null,b)}};a.wrap=function(a,
b){return function(){var c=[a];return l.apply(c,arguments),b.apply(this,c)}};a.compose=function(){var a=arguments;return function(){for(var b=arguments,c=a.length-1;0<=c;c--)b=[a[c].apply(this,b)];return b[0]}};a.after=function(a,b){return 0>=a?b():function(){return 1>--a?b.apply(this,arguments):void 0}};a.keys=x||function(b){if(b!==Object(b))throw new TypeError("Invalid object");var c=[],d;for(d in b)a.has(b,d)&&(c[c.length]=d);return c};a.values=function(b){var c=[],d;for(d in b)a.has(b,d)&&c.push(b[d]);
return c};a.pairs=function(b){var c=[],d;for(d in b)a.has(b,d)&&c.push([d,b[d]]);return c};a.invert=function(b){var c={},d;for(d in b)a.has(b,d)&&(c[b[d]]=d);return c};a.functions=a.methods=function(b){var c=[],d;for(d in b)a.isFunction(b[d])&&c.push(d);return c.sort()};a.extend=function(a){return r(u.call(arguments,1),function(b){if(b)for(var c in b)a[c]=b[c]}),a};a.pick=function(a){var b={},c=z.apply(q,u.call(arguments,1));return r(c,function(c){c in a&&(b[c]=a[c])}),b};a.omit=function(b){var c=
{},d=z.apply(q,u.call(arguments,1)),f;for(f in b)a.contains(d,f)||(c[f]=b[f]);return c};a.defaults=function(a){return r(u.call(arguments,1),function(b){if(b)for(var c in b)null==a[c]&&(a[c]=b[c])}),a};a.clone=function(b){return a.isObject(b)?a.isArray(b)?b.slice():a.extend({},b):b};a.tap=function(a,b){return b(a),a};var p=function(b,c,d,f){if(b===c)return 0!==b||1/b==1/c;if(null==b||null==c)return b===c;b instanceof a&&(b=b._wrapped);c instanceof a&&(c=c._wrapped);var g=D.call(b);if(g!=D.call(c))return!1;
switch(g){case "[object String]":return b==c+"";case "[object Number]":return b!=+b?c!=+c:0==b?1/b==1/c:b==+c;case "[object Date]":case "[object Boolean]":return+b==+c;case "[object RegExp]":return b.source==c.source&&b.global==c.global&&b.multiline==c.multiline&&b.ignoreCase==c.ignoreCase}if("object"!=typeof b||"object"!=typeof c)return!1;for(var h=d.length;h--;)if(d[h]==b)return f[h]==c;d.push(b);f.push(c);var h=0,l=!0;if("[object Array]"==g){if(h=b.length,l=h==c.length)for(;h--&&(l=p(b[h],c[h],
d,f)););}else{var g=b.constructor,m=c.constructor;if(g!==m&&!(a.isFunction(g)&&g instanceof g&&a.isFunction(m)&&m instanceof m))return!1;for(var n in b)if(a.has(b,n)&&(h++,!(l=a.has(c,n)&&p(b[n],c[n],d,f))))break;if(l){for(n in c)if(a.has(c,n)&&!h--)break;l=!h}}return d.pop(),f.pop(),l};a.isEqual=function(a,b){return p(a,b,[],[])};a.isEmpty=function(b){if(null==b)return!0;if(a.isArray(b)||a.isString(b))return 0===b.length;for(var c in b)if(a.has(b,c))return!1;return!0};a.isElement=function(a){return!(!a||
1!==a.nodeType)};a.isArray=G||function(a){return"[object Array]"==D.call(a)};a.isObject=function(a){return a===Object(a)};r("Arguments Function String Number Date RegExp".split(" "),function(b){a["is"+b]=function(a){return D.call(a)=="[object "+b+"]"}});a.isArguments(arguments)||(a.isArguments=function(b){return!(!b||!a.has(b,"callee"))});"function"!=typeof/./&&(a.isFunction=function(a){return"function"==typeof a});a.isFinite=function(a){return isFinite(a)&&!isNaN(parseFloat(a))};a.isNaN=function(b){return a.isNumber(b)&&
b!=+b};a.isBoolean=function(a){return!0===a||!1===a||"[object Boolean]"==D.call(a)};a.isNull=function(a){return null===a};a.isUndefined=function(a){return void 0===a};a.has=function(a,b){return C.call(a,b)};a.noConflict=function(){return c._=d,this};a.identity=function(a){return a};a.times=function(a,b,c){for(var d=Array(a),f=0;a>f;f++)d[f]=b.call(c,f);return d};a.random=function(a,b){return null==b&&(b=a,a=0),a+Math.floor(Math.random()*(b-a+1))};var K={escape:{"\x26":"\x26amp;","\x3c":"\x26lt;",
"\x3e":"\x26gt;",'"':"\x26quot;","'":"\x26#x27;","/":"\x26#x2F;"}};K.unescape=a.invert(K.escape);var A={escape:RegExp("["+a.keys(K.escape).join("")+"]","g"),unescape:RegExp("("+a.keys(K.unescape).join("|")+")","g")};a.each(["escape","unescape"],function(b){a[b]=function(a){return null==a?"":(""+a).replace(A[b],function(a){return K[b][a]})}});a.result=function(b,c){if(null==b)return null;var d=b[c];return a.isFunction(d)?d.call(b):d};a.mixin=function(b){r(a.functions(b),function(c){var d=a[c]=b[c];
a.prototype[c]=function(){var b=[this._wrapped];return l.apply(b,arguments),T.call(this,d.apply(a,b))}})};var Q=0;a.uniqueId=function(a){var b=++Q+"";return a?a+b:b};a.templateSettings={evaluate:/<%([\s\S]+?)%>/g,interpolate:/<%=([\s\S]+?)%>/g,escape:/<%-([\s\S]+?)%>/g};var S=/(.)^/,P={"'":"'","\\":"\\","\r":"r","\n":"n","\t":"t","\u2028":"u2028","\u2029":"u2029"},J=/\\|'|\r|\n|\t|\u2028|\u2029/g;a.template=function(b,c,d){var f;d=a.defaults({},d,a.templateSettings);var g=RegExp([(d.escape||S).source,
(d.interpolate||S).source,(d.evaluate||S).source].join("|")+"|$","g"),h=0,l="__p+\x3d'";b.replace(g,function(a,c,d,f,g){return l+=b.slice(h,g).replace(J,function(a){return"\\"+P[a]}),c&&(l+="'+\n((__t\x3d("+c+"))\x3d\x3dnull?'':_.escape(__t))+\n'"),d&&(l+="'+\n((__t\x3d("+d+"))\x3d\x3dnull?'':__t)+\n'"),f&&(l+="';\n"+f+"\n__p+\x3d'"),h=g+a.length,a});l+="';\n";d.variable||(l="with(obj||{}){\n"+l+"}\n");l="var __t,__p\x3d'',__j\x3dArray.prototype.join,print\x3dfunction(){__p+\x3d__j.call(arguments,'');};\n"+
l+"return __p;\n";try{f=Function(d.variable||"obj","_",l)}catch(m){throw m.source=l,m;}if(c)return f(c,a);c=function(b){return f.call(this,b,a)};return c.source="function("+(d.variable||"obj")+"){\n"+l+"}",c};a.chain=function(b){return a(b).chain()};var T=function(b){return this._chain?a(b).chain():b};a.mixin(a);r("pop push reverse shift sort splice unshift".split(" "),function(b){var c=q[b];a.prototype[b]=function(){var a=this._wrapped;return c.apply(a,arguments),"shift"!=b&&"splice"!=b||0!==a.length||
delete a[0],T.call(this,a)}});r(["concat","join","slice"],function(b){var c=q[b];a.prototype[b]=function(){return T.call(this,c.apply(this._wrapped,arguments))}});a.extend(a.prototype,{chain:function(){return this._chain=!0,this},value:function(){return this._wrapped}})}).call(this);
/*46587 g*//* TNZPRDWEB2 */